Fix x86 build with cygwin32

diff --git a/defs/managed-components b/defs/managed-components
--- a/defs/managed-components
+++ b/defs/managed-components
@@ -1,6 +1,6 @@
-#!/bin/bash -xe
+#!/usr/bin/bash -xe
 
-REPO=${2:-"http://storage.bos.internalx.com/mono-mac-4.0.0-branch/79/7975f5090d8b0d266dc0ba824295d92edd8873da/MonoFramework-MDK-4.0.0.0.macos10.xamarin.x86.pkg"}
+REPO=${2:-"https://download.mono-project.com/archive/nightly/macos-10-universal/MonoFramework-MDK-5.3.0.465.macos10.xamarin.universal.pkg"}
 REPODIR=$(dirname $(realpath $0))/../repos/managed-components
 
 error()
@@ -18,7 +18,7 @@ download()
 {
 	mkdir -p ${REPODIR}
 	report "Downloading Xar"
-	wget --quiet -O ${REPODIR}/xar.tar.gz https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/xar/xar-1.5.2.tar.gz || error "*** Could not download Xar ***"
+	wget --quiet -O ${REPODIR}/xar.tar.gz https://f001.backblazeb2.com/file/nanobot/xar-2.0.0.tar.gz || error "*** Could not download Xar ***"
 	report "Downloading Mono MDK for Mac - ${REPO}"
 	wget --quiet -O ${REPODIR}/mono.xar ${REPO}
 }
@@ -40,17 +40,20 @@ clean()
 build()
 {
 	pushd ${REPODIR}
-	if [ ! -x "${REPODIR}/xar/src/xar" ]
+	if [ ! -x "${REPODIR}/xar/xar/src/xar.exe" ]
 		then report "Building Xar"
 		mkdir -p xar
 		tar xf xar.tar.gz -C xar/ --strip-components=1
 		pushd xar/
-		./configure
+		./autogen.sh
+		cd xar
+		./configure --host=i686-pc-cygwin --enable-static --disable-shared --without-bzlib
+		make clean
 		make
 		popd
 	fi
 	report "Unpacking Mono for Mac"
-	xar/src/xar -x -f mono.xar
+	xar/xar/src/xar.exe -x -f mono.xar
 	zcat mono.pkg/Payload | bsdcpio -i
 	mv Library/Frameworks/Mono.framework/Versions/5.* mono-mac
 	popd
@@ -90,8 +93,8 @@ install()
 		sed -i 's#/Library.*mono #\"\$\{BASH_SOURCE%/\*\}\"/mono #' $i
 		sed -i 's#/Library.*cli #\"\$\{BASH_SOURCE%/\*\}\"/cli #' $i
 		if [ -n "$(grep -hoE '[\" ]/Library.*\.(exe|dll)' $i)" ]
-			then EXENAME=$(basename `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/^\"//'`)
-			RUNTIME=$(dirname `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i` | sed 's/^\"//' | sed 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##')
+			then EXENAME=$(basename `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/"//g' | sed 's/$MONO_OPTIONS//g' | sed 's/.*[[:space:]]//'`)
+			RUNTIME=$(dirname `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/$MONO_OPTIONS//g'` | sed 's/^\"//' | sed 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##' | sed '$!d')
 			sed "s#@@RUNTIME@@#${RUNTIME}\\\\#g" ${REPODIR}/../../resources/wrapper.bat > $i.bat
 			sed -i "s#@@COMMAND@@#${EXENAME}#g" $i.bat
 			sed -i 's#/#\\#g' $i.bat
diff --git a/defs/mono b/defs/mono
--- a/defs/mono
+++ b/defs/mono
@@ -1,4 +1,4 @@
-#!/bin/bash -xe
+#!/usr/bin/bash -xe
 
 REPO=https://github.com/mono/mono.git
 REPODIR=$(dirname $(realpath $0))/../repos/mono
@@ -41,6 +41,8 @@ clean()
 	report "Running git clean and reset"
 	git clean -fdx || error "*** Could not run git clean ***"
 	git reset --hard HEAD || error "*** Could not run git reset ***"
+	report "Running git pull"
+	git pull || error "*** Could not run git pull ***"
 	popd
 	wget --quiet -O ${REPODIR}/pkgconfig.zip http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip
 }
